apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-publisher-deploy
  labels:
    app: sp-publisher
spec:
  replicas: 3
  selector:
    matchLabels:
       app: sp-publisher
  template:
    metadata: 
      name: sp-publisher-pod
      labels:
        app: sp-publisher
    spec:
      containers:
      - name: sp-publisher
        image: conflowence/sp-publisher
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbit-mq-svc"
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: my-publisher-svc
spec:
  type: LoadBalancer
  selector:
    app: sp-publisher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 31515