apiVersion: v1
kind: Pod
metadata: 
  name: rabbit-pod
  labels:
    component: rabbitmq-server
spec:
  containers:
  - name: sp-publisher
    image: rabbitmq:3.9-management
    ports:
    - containerPort: 5672
    - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-svc
spec:
  type: LoadBalancer
  selector:
    component: rabbitmq-server
  ports:
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30000
    - name: service
      protocol: TCP
      port: 5672
      targetPort: 5672