version: '3'
services:
  rabbit-mq:
    image: rabbitmq:3.9-management
    container_name: rabbit-mq  
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      
  producer-sp:
    build: .
    ports:
      - "9000:9000"
    environment:
        - SPRING_RABBITMQ_HOST=rabbit-mq 
    depends_on:                           #define dependencies of this app
      - rabbit-mq

  consumer-sp:
    build:
      dockerfile: Dockerfile
      context: ../consumer
    environment:
        - SPRING_RABBITMQ_HOST=rabbit-mq 
    depends_on:                           #define dependencies of this app
      - rabbit-mq